default_case_id: encyclopedia
cases:
  encyclopedia:
    skill_name: encyclopedia
  story_book:
    skill_name: story-book
  behavior_correction:
    skill_name: behavior-correction
  classic_poetry_book:
    skill_name: classic-poetry-book
